swagger: '2.0'

info:
  version: '1.0.0'
  title: APIS
  description: 'APIS'

paths:
  /pokemon/listpokemones?limite=10:
    get:
      tags:
        - pokemon
      produces:
        - application/json
      responses:
        '200':
          description: Success
          schema:
            title: pokemon
            type: array
            items:
              $ref: '#/definitions/pokemon'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
 

 
definitions:    
  pokemon:
   type: object
   properties:
     name:
        type: string
     numberEuros:
        type: string

  Error:
    type: object
    properties:
      title:
        type: string
      type:
        type: string
      detail:
        type: string
      instance:
        type: string
      invalidparams:
        type: string
